apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835-final-cluster
  region: us-east-1
  version: "1.30"

# Disable Auto Mode to prevent permission errors
autoModeConfig:
  enabled: false

# CLUSTER ROLE (The long one you found)
iam:
  serviceRoleARN: "arn:aws:iam::975050319979:role/c177358a4583888l11469873t1w975050-LabEksClusterRole-4mwNpA5Nk2kK"

managedNodeGroups:
  - name: standard-workers
    instanceType: t3.medium
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    # WORKER ROLE (Standard LabRole)
    iam:
      instanceRoleARN: "arn:aws:iam::975050319979:role/LabRole"