apiVersion: v1
kind: ServiceAccount
metadata:
  name: clo835
  namespace: final
  annotations:
    # This ARN allows the pod to talk to S3. 
    # If you don't have the specific ARN yet, keep this placeholder.
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/service-role-name"