kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: final
  name: CLO835
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clo835-binding
  namespace: final
subjects:
- kind: ServiceAccount
  name: clo835
  namespace: final
roleRef:
  kind: Role
  name: CLO835
  apiGroup: rbac.authorization.k8s.io