apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      serviceAccountName: clo835
      containers:
      - name: flask-app
        # REPLACE THE ACCOUNT ID BELOW with your actual AWS Account ID
        image: 975050350494.dkr.ecr.us-east-1.amazonaws.com/clo835-final-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 81
        env:
        # Database Host: Matches the name of the Service in file 05-mysql-service.yaml
        - name: MYSQL_HOST
          value: "mysql-service"
        # Database Name
        - name: MYSQL_DB
          value: "employees"
        # Database User & Password (From Secrets)
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        # App Configuration (From ConfigMap)
        - name: BG_IMAGE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BG_IMAGE_URL
        - name: HEADER_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: HEADER_NAME
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"