apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: final
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80        # The port you visit in the browser
      targetPort: 81  # The port the container listens on
  type: LoadBalancer